### ISSUE TITLE
Incorrect import when generating

### ISSUE THREAD

**Issue by ilopX** [timsneath/winmd#3]
When I run ```dart example/main.dart ```
I get this error
![image](https://user-images.githubusercontent.com/8049534/107515627-f47bbc80-6bb3-11eb-8737-4af79689d6d8.png)

I manually changed all red imports to ```import 'package:win32/win32.dart';```

**Comment by timsneath** [comment]
Those files shouldn't be there -- they're not in the repo at that location, at least in the `main` branch. They come from the `win32` package, rather than the `winmd` package. Did I accidentally check them in at some point? Or did you perhaps run the generate batch file from `win32` in the wrong folder?

**Comment by timsneath** [comment]
Closing for now. Please reopen if you're still seeing this!
